### ISSUE TITLE
PositionStore issue

### ISSUE THREAD

**Issue by BroiSatse** [eventide-project/consumer-event-store#1]
Hi All,

I am playing with Eventide a bit and i noticed a weird behaviour with Consumer - when restarted it always replays the very last event from the topic. I had dig in and it seems to be caused by PositionStore which stores the global_position of the last handled event and then it uses it as a started position on consumer. At the moment I got around this with:

```
module Consumer
  module EventStore
    class PositionStore
      module ConsumerFix
        def get
          super + 1
        end
      end

      prepend ConsumerFix
    end
  end
end

```

Which is not ideal, but was the simplest monkey patching point. Is it a bug or am I using it incorrectly?

**Comment by ntl** [comment]
The intention of the position store is to _periodically_ record a position. The default position update interval is 100, see https://github.com/eventide-project/consumer/blob/master/lib/consumer/defaults.rb#L3-L5

If the position update interval is 100, that means a recent position offset is only recorded every 100 messages. That means there's only a 1 in 100 chance for a consumer that restarts to pick up _exactly_ where it left off. This means that all message handlers have to anticipate _cycling through_ messages that have already been processed.

There is no way that position stores -- even at a position update interval of 1 (every message) -- could guarantee that messages are never handled more than once -- that would essentially be "exactly once message delivery," which is impossible.I think that your expectations are incorrect _if_ you're expecting to use offsets to process each message exactly once. Instead, ensure that your message handlers are idempotent, so that you don't have to worry about recycling some number of messages whenever your consumer restarts.

However, it strikes me as overly defensive that the consumers start one message _before_ the last recorded position. If the position store records that the message at position 900 was processed, and then later records that the message at position 1,000 was processed, it should probably restart at message 901, or 1,001, respectively.

**Comment by ntl** [comment]
I'm going to close this we did not identify a necessary improvement that could be made.
